### PR TITLE
feat(274): [prefer-immediate-return] ignore when returned variable has a declared type

### LINKED ISSUE #274: Improve 'prefer-immediate-return': ignore when returned variable has a declared type
In 'prefer-immediate-return' when returned variable declaration has a declared type it could be sometimes error-prone to drop this typed declaration
See detailed example https://community.sonarsource.com/t/immediately-returned-variable-rule-conflicts-with-typescript-excess-property-checking/30870

```
function foo() {
  let x: SomeType = ...; // do not report if declaration has a type
  return x; 
}
```

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #274

### CODE REVIEW

**Comment by vilchik-elena** [comment]
@a-tarasyuk thanks for the contribution! Merged as part of #277

**Comment by a-tarasyuk** [comment]
@vilchik-elena Thanks. Were there any issues with this PR that made the merge impossible?

**Comment by a-tarasyuk** [comment]
@vilchik-elena Thanks. Were there any issues with this PR that made the merge impossible?

**Comment by vilchik-elena** [comment]
@a-tarasyuk no, we just need to have a PR open by sonarsourcer to have build running

**Pull request closed without merging**
