### PR TITLE
feat: add 'meta.docs'

### PR DESCRIPTION
**Pull request by Loxos**
Eslint does support a documentation section in rule definitions. This section allows IDE plugins to display rule descriptions and directly link to the rule documentation. Details are documentad at:
https://eslint.org/docs/developer-guide/working-with-rules#rule-basics

### CODE REVIEW

**Comment by Loxos** [comment]
Hey,
This is my first PR around here, I hope this still provides value. 
Prettier automatically cleaned up a few minor changes in the rule files.
Should I revert these changes to keep this PR limited to the doc-sections?

**Comment by brettz9** [comment]
Such changes are implemented in our fork at https://github.com/es-joy/eslint-plugin-radar

**Comment by brettz9** [comment]
Sorry last comment was for wrong issue! Will delete these comments.

**Comment by brettz9** [comment]
This has been incorporated (changing the URL for our repo) in our fork at https://github.com/es-joy/eslint-plugin-radar and `eslint-plugin-radar@0.2.0`

**Comment by vilchik-elena** [comment]
@Loxos Thanks for the contribution!

Will be soon merged as part of https://github.com/SonarSource/eslint-plugin-sonarjs/pull/246

**Pull request closed without merging**
