### PR TITLE
[DO NOT MERGE] BUILD-4777 fix prepack build error

### PR DESCRIPTION
**Pull request by hedinasr**

### CODE REVIEW

**Comment by zglicz** [comment]
@hedinasr - do you have a timeline for when this can be fixed?

**Comment by hedinasr** [comment]
the issue was fixed by updating the jfrog cli. Closing this PR.

**Comment by ilia-kebets-sonarsource** [comment]
Hey @hedinasr, could you link here the commit or PR that updated the jfrog cli?

**Comment by hedinasr** [comment]
the jfrog-cli is installed using the `apt` package manager so it was not a direct upgrade from us, rather it was by the jfrog team. We just had to rebuild the base image and the package was updated.

**Comment by hedinasr** [comment]
but you can check [here](https://releases.jfrog.io/artifactory/jfrog-debs/pool/jfrog-cli-v2/) and see that the package was added the `17-Apr-2024 07:26`.

**Comment by ilia-kebets-sonarsource** [comment]
I confirm that [it's fixed](https://cirrus-ci.com/build/6253924129177600). Thank you for your help, @hedinasr !

**Pull request closed without merging**
