### PR TITLE
Editorconfig

### PR DESCRIPTION
**Pull request by brettz9**
- Add `.editorconfig` for before-the-fact IDE placement of indents

### CODE REVIEW

**Comment by vilchik-elena** [comment]
Is plugin required to use this config file? Which IDEs are supported? 
TBH I'm not convinced we need this change.

**Comment by brettz9** [comment]
[EditorConfig](https://editorconfig.org) is a widely used standard for ensuring that (mostly language-independent) features such as indents are set intelligently before-the-fact--i.e., there is no need for waiting for linting, or using auto-lint fixers (which may apply other fixes one doesn't want). Instead, as soon as you hit enter, it sets the proper indent.

You can see a good list of IDEs which have support built-in at https://editorconfig.org/#download , and other IDEs which have support via plug-in: https://editorconfig.org/#download

It make contributing easier. I can add it to `.npmignore` to make it even less obtrusive.

**Comment by brettz9** [comment]
I've added to `.npmignore`.

**Comment by brettz9** [comment]
The Travis build was failing for some reason on the config, so I squashed the commits to force a rebuild and now it is passing.

Btw, it may be of interest to note that both ESLint and TypeScript themselves have an `.editorconfig`: https://github.com/eslint/eslint/blob/master/.editorconfig and https://github.com/microsoft/TypeScript/blob/master/.editorconfig

Also, let me know if you want me to remove the `sudo: false` and `notifications -> on_start` which appear now to have no effect per the project's Travis website:

image

**Comment by saberduck** [comment]
thanks for this contribution :+1:

**Pull request merged**
