### PR TITLE
Allow ESLint 7 as a peer dependency

### PR DESCRIPTION
**Pull request by adp-psych**
ESLint 7 has been out for a while now, and this plugin works fine with it.

### CODE REVIEW

**Comment by timwright12** [comment]
+1

**Review by Zialus — APPROVED** [review]

**Comment by Ionaru** [comment]
@Zialus Duplicate of #180

**Review by Loxos — APPROVED** [review]

**Comment by brettz9** [comment]
For any watchers, this is implemented now in a fork at https://github.com/es-joy/eslint-plugin-radar

**Comment by yassin-kammoun-sonarsource** [comment]
Duplicate #194

**Pull request closed without merging**
