### PR TITLE
Add min lines configuration for no-identical-functions rule

### LINKED ISSUE #225: Minimum required functions line of rule `no-identical-functions` can be configured
**I want to request a feature.**
Hello.
I want a feature that the minimum required functions line of rule `no-identical-functions` can be configured by user.
Now is a fixed value 2.
https://github.com/SonarSource/eslint-plugin-sonarjs/blob/master/src/rules/no-identical-functions.ts#L66

I can contribute to this feature if need any helps.

### PR DESCRIPTION
**Pull request by vanyaraspopov**
Fixes #225

### CODE REVIEW

**Comment by vanyaraspopov** [comment]
Hello? Anybody home?
Please let me know about the term you can review my fix.

**Comment by vilchik-elena** [comment]
Hi @vanyaraspopov,

We don't think it's a good idea to have this parameter configured by user. 
What would be the use-cases when you would allow duplications of bigger functions?

**Comment by vanyaraspopov** [comment]
Hi @vilchik-elena , thanks for your reply!

I'd like to leave small duplications rather than try to refactor that because it produces an extra code bigger than duplication itself or it takes a lot of time.

Generally I can say that I run into some issues with callbacks.

For example, react component in storybook.
```jsx
const ComponentStories = () => {
  return (
    <div>
      {cases1.map((props, i) => (
        <div key={i}>
          <Component />
        </div>
      ))}
      {cases2.map((props, i) => (
        <div key={i}>
          <Component />
        </div>
      ))}
    </div>
  );
};
```

or this example
```js
function foo() {
  const someVarWithLongName = "a";
  const anotherVarWithLongName = "b";
  baz(() => {
    console.log({
      someVarWithLongName,
      anotherVarWithLongName,
    });
  });
}

function bar() {
  const someVarWithLongName = "x";
  const anotherVarWithLongName = "y";
  baz(() => {
    //---^^ no-identical-functions
    console.log({
      someVarWithLongName,
      anotherVarWithLongName,
    });
  });
}

function baz(callback) {
  // do some stuff
  callback();
}
```

**Comment by vilchik-elena** [comment]
@vanyaraspopov I understand that those are just examples and probably in real life the reported issues are harder to refactor but here I don't see any problem with refactoring.

```jsx
const ComponentStories = () => {
  const componentInDiv = key => (<div key={i}>
          <Component />
        </div>);
  return (
    <div>
      {cases1.map((_, i) => componentInDiv(i))}
      {cases2.map((_, i) => componentInDiv(i))}
    </div>
  );
};
```


```js
function helper(var1, var2) {
  const someVarWithLongName = var1;
  const anotherVarWithLongName = var2;
  baz(() => {
    console.log({
      someVarWithLongName,
      anotherVarWithLongName,
    });
  });
}

function foo() {
  helper("a", "b");
}

function bar() {
  helper("x", "y");
}

function baz(callback) {
  // do some stuff
  callback();
}
```

If it's hard to refactor or you don't want (e.g. you know you will change one duplicate later), you can disable the issue with a comment.

I am happy to hear more reasons to disable the rule for bigger functions if you have smth else in mind

**Comment by vanyaraspopov** [comment]
Yes, those examples are simple just for demo but talking about first one I see no considerable difference. The second example came out oversimplified, my bad. I could think up a better one but it's not worth. The main idea I want to express is that small duplications are acceptable and I'd like to tune the size of it with the option. Also it would be better to avoid suppressing comments because it may become a common practice.

**Comment by vilchik-elena** [comment]
Finally our team decided to accept this config, I opened a PR https://github.com/SonarSource/eslint-plugin-sonarjs/pull/325 to include your contribution. Thanks! 
Note that I had to adjust the options scheme as we want to accept single `sonar-runtime`

**Pull request closed without merging**
