### PR TITLE
Updated peerDependencies to include eslint ^7

### PR DESCRIPTION
**Pull request by ghoshArnab**
Fixes #

### CODE REVIEW

**Comment by constgen** [comment]
I think Node 8 should also be removed from Travis config as it is deprecated by ESlint 7

**Comment by brettz9** [comment]
Note that this is also handled (with Node 8 Travis removal) in #155 , so if that may be accepted, there will be no need for this PR.

**Comment by brettz9** [comment]
Now handled in fork at https://github.com/es-joy/eslint-plugin-radar

**Comment by yassin-kammoun-sonarsource** [comment]
Duplicate #194

**Pull request closed without merging**
