### PR TITLE
add eslint 6 to peerDeps

### LINKED ISSUE #120: Add eslint v6.0 as peer dependency
**I want to request a feature.**

Please bump support for eslint 6.0. I've been using it internally for several weeks, and it seems to work fine.

### PR DESCRIPTION
**Pull request by brettz9**
Fixes #120

### CODE REVIEW

**Comment by 7rulnik** [comment]
@andrea-guarino-sonarsource hey! Can we merge it? :)
Some people use `npm ls` on CI as a way to check that all peerDeps are installed. So, this is blocker for them to upgrade to eslint@6

**Comment by andrea-guarino-sonarsource** [comment]
Hi @7rulnik and @brettz9 ,
Currently we're not working on our JavaScript analizer, but we should have a sprint pretty soon.
We'll need to go through breaking changes listed [here](https://eslint.org/docs/user-guide/migrating-to-6.0.0) and release a new version of `eslint-plugin-sonarjs`.

**Comment by brettz9** [comment]
FWIW, I've been using with eslint 6 and there don't seem to be any issues, but of course I understand the need for a review.

**Comment by 7rulnik** [comment]
Seems that we only should bump nodejs version in package.json

**Comment by vilchik-elena** [comment]
Hi @brettz9,
All good, only one thing. Could you update min NodeJS version (>=8.x) in readme?

**Comment by brettz9** [comment]
Sure, @vilchik-elena , I can do that, but I'm not sure that you strictly speaking need to do so, since, in your `package.json`, `engines` is still showing `">=6"` and `peerDependencies` is still showing support for older eslint versions which don't require Node 8.

Your own code could thus continue to support older Node versions (as long as users didn't update eslint to 6)--unless that is, you have made other updates to your own code base recently which in fact depend on Node 8 features.

FYI, `.travis.yml` is still running against Node 6 and 8 (only), so this should probably be updated as well, depending on what you want--i.e., removing Node 6 if you want to drop support, and in any case, presumably also adding tests against Node 10 and 12.

However, if you do want to drop Node 6 support (as many projects are admittedly doing), then you might consider whether you also wish to limit the eslint versions you support.

Note that if you keep Node 6 support and want to ensure Travis is testing such a version as you advertise supporting, special logic will need to be added to ensure the Node 6 environment is installing an earlier eslint version. Likewise if you want to keep support for older eslint versions and test these (even if you run them on Node 8).

**Comment by brettz9** [comment]
any chance for a release?

**Pull request merged**
